### PR TITLE
Use sparkling-water-package as the artifact

### PR DESCRIPTION
**Pull request by jakubhava**
This artefact contain all relevant sparkling water dependencies

### CODE REVIEW

**Comment by navdeep-G** [comment]
@jakubhava Can you investigate the failures?

**Comment by jakubhava** [comment]
@navdeep-G should be resolved, I left additional comma there after initial change which was breaking the build.

**Comment by jakubhava** [comment]
Oki, something is still going wrong. Maybe it's related to the packaging issues of our artifacts. Will have a look on it when I know more

**Comment by navdeep-G** [comment]
@jakubhava Sounds good. Let me know how I can help. Once this is in I will prep for another rsparkling release to CRAN

**Comment by navdeep-G** [comment]
@jakubhava I can take a look

**Comment by navdeep-G** [comment]
Will close for now. Please reopen if needed.

**Comment by jakubhava** [comment]
Please keep it open, it's a good change, we just need to find a good time :)

**Comment by jakubhava** [comment]
So found a reason why this is failing. We use in tests Sparkling Water versions for which there is no `sparkling_water_package` package as it was introduced quite recently. The solution is simple - tests on latest Sparkling Water versions which is implemented in https://github.com/h2oai/rsparkling/pull/76

**Comment by jakubhava** [comment]
I based this PR on https://github.com/h2oai/rsparkling/pull/76 where the versions are updated

**Comment by jakubhava** [comment]
I'm gonna close this PR. This change is good( and works on latest Sparkling Water for Spark 2.2, 2.1 and 2.0), however it would fail for older Sparkling Water versions for which the package `sparkling-water-package` does not exist. 

The functionality of RSparkling remains unchanged

**Pull request closed without merging**
