### PR TITLE
Update SW version info & travis file

### PR DESCRIPTION
**Pull request by navdeep-G**

### CODE REVIEW

**Comment by jakubhava** [comment]
To support Sparkling Water 2.2 we also need to do changes in code.

**Comment by navdeep-G** [comment]
@jakubhava will add that. thx

**Comment by jakubhava** [comment]
@navdeep-G you're right, I just missed that. Thanks for the change!

**Comment by navdeep-G** [comment]
@jakubhava Yep, right now travis will test latest SW across Spark 1.6,2.0,2.1, and 2.2.

**Pull request merged**
