### PR TITLE
Automatically decipher Sparkling Water version based on Spark version

### PR DESCRIPTION
**Pull request by navdeep-G**
* This PR will do the following:

1. If `sw_version` & `sw_location` are not set, then `spark_dependencies()` will look for the version of Spark installed. If it is `2.0`, then we fetch the latest Sparkling Water for Spark 2.0. If it is `1.6`, then we fetch the latest Sparkling Water for Spark 1.6. Otherwise it will thrown an error.
2. The user will be prompted as to which H2O version should be installed for each of the above versions of Sparkling Water. 

This should make it a bit more straight forward in terms of installing `rsparkling`. A user does not need to set `options(sw_version = ...)` if they choose not too. The only manual task a user is left with is ensuring their version of H2O is compliant with their version of Sparkling Water.

### CODE REVIEW

**Comment by javierluraschi** [comment]
@navdeep-G  Rather than prompting the user which version of H2O to install, I believe we should rather pick the "best"/latest version of H2O for the user by default, but allow advanced users to configure this out.

**Comment by navdeep-G** [comment]
@javierluraschi The version of H2O provided is the one compliant with that specific version of Sparkling Water. In this case, it is the one compliant with the latest Sparkling Water for Spark 2.0 or Spark 1.6. And by "pick" do you mean "install"?

**Comment by javierluraschi** [comment]
@navdeep-G I might be misunderstanding this comment: "The user will be prompted as to which H2O version should be installed for each of the above versions of Sparkling Water.". What do we mean by "prompt"? Can you point me to the code that would cause the prompt? My point was that we should never prompt the user for information while using the default settings, if this is not the case, please ignore my comment.

**Comment by navdeep-G** [comment]
Sorry, not really "prompted", but "informed".

**Comment by javierluraschi** [comment]
@navdeep-G that's totally fine.

Being a bit nit picky, I think we should not print this information at all but ideally, print this information when the connection fails (during `spark_connect`) by not meeting the requirements.

If this is not possible, or preffer to keep the message, I believe you would want to use `message` instead `cat` since `message` can be silenced with `suppressMessages` if users finds this too verbose.

**Comment by navdeep-G** [comment]
The connect should not fail due to a difference in H2O version. The mismatch error would happen when calling h2o functions from RSparkling(h2o_context,etc).

Adding 'message' instead of 'cat' sounds good.

**Comment by ledell** [comment]
I made some updates to the message so that it will say something like this if you have the wrong h2o version installed (and provide a clean code block for copy/pasting):
```{r}
> sc <- spark_connect(master = "local", version = "1.6.2")
Spark version 1.6 detected. Will call latest Sparkling Water version 1.6.8

Detected H2O version 3.10.1.2. Please install H2O version 3.10.0.7, which is compliant with the latest Sparkling Water version 1.6.8

To update your h2o R package, copy/paste the following commands and then restart your R session:

  detach("package:rsparkling", unload=TRUE)
  if ("package:h2o" %in% search()) { detach("package:h2o", unload=TRUE) }
  if (isNamespaceLoaded("h2o")){ unloadNamespace("h2o") }
  remove.packages("h2o")
  install.packages("h2o", type="source", repos= "http://h2o-release.s3.amazonaws.com/h2o/rel-turing/7/R")
```

**Comment by ledell** [comment]
One thing that is sort of confusing is that (at least for Spark 1.6.2), after you update your h2o package to the correct version, you get this sort of misleading note from h2o (which encourages you to upgrade your h2o package):

```
> training <- as_h2o_frame(sc, partitions$training, strict_version_check = FALSE)
Warning message:
In h2o.clusterInfo() :
Your H2O cluster version is too old (4 months and 13 days)!
Please download and install the latest version from http://h2o.ai/download/
```

**Pull request merged**
