### PR TITLE
Update release process for RSparkling

### PR DESCRIPTION
**Pull request by navdeep-G**
* This PR updates the release process for RSparkling by making it a little simpler. 
* To build a RSparkling release you must do the following:
```
cd before_release/
bash prepare_release.sh release
```
* The above will then build a new `.tar.gz` file with an updated minor version, which can then be submitted to CRAN.
* If you just want to update the release table and not update the version/build a release artifact then do the following:
```
cd before_release/
bash prepare_release.sh
```

### CODE REVIEW

**Comment by jakubhava** [comment]
Perfect, thanks @navdeep-G. How do you create release tag on GitHub, manually? I can automate this in the same way we have for Sparkling Water, just don't want to duplicate any effort.

Thanks!

**Comment by navdeep-G** [comment]
@jakubhava Right now it is done manually, but feel free to automate. I assume you mean these? https://github.com/h2oai/rsparkling/releases

**Comment by jakubhava** [comment]
Cool I see, thanks!

I will make whole this as part of SW pipeline and upload the resulting tar.gz file to S3. To create release to cran, one should upload the artifact from that location.  Thanks for helping with this!

**Review by jakubhava — APPROVED** [review]
Thx @navdeep-G!

**Pull request merged**
